name: deploy-client
on:
    push:
        branches:
            - master
        # paths: 
        #     - 'client/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2
            
            - name: build docker image
              run: cd client && docker build -t ${{secrets.GKE_REGISTRY_URL}}/${{secrets.GKE_PROJECT_ID}}/client .

            - name: Setup google cloud
              uses: google-github-actions/auth@v1
              with:
                project_id: ${{secrets.GKE_PROJECT_ID}} 
                credentials_json: ${{secrets.GKE_APPLICATION_CREDENTIALS}}
            
            - name: Push docker image
              env: 
                GOOGLE_PROJECT: ${{secrets.GKE_PROJECT_ID}}
              run: 
                gcloud auth configure-docker &&
                docker push ${{secrets.GKE_REGISTRY_URL}}/${{secrets.GKE_PROJECT_ID}}/client
            