name: deploy-comments
on:
    push:
        branches:
            - master
        # paths: 
        #     - 'comments/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2
            
            - name: build docker image
              run: cd comments && docker build -t ${{secrets.GKE_REGISTRY_URL}}/${{secrets.GKE_PROJECT_ID}}/comments .

            - name: Setup google cloud
              uses: google-github-actions/auth@v1
              with:
                project_id: ${{secrets.GKE_PROJECT_ID}} 
                credentials_json: ${{secrets.GKE_APPLICATION_CREDENTIALS}}
            
            - name: Push docker image
              env: 
                GOOGLE_PROJECT: ${{secrets.GKE_PROJECT_ID}}
              run: 
                gcloud auth configure-docker &&
                docker push ${{secrets.GKE_REGISTRY_URL}}/${{secrets.GKE_PROJECT_ID}}/comments

            - name: Connect to GKE
              uses: google-github-actions/get-gke-credentials@v0
              with:
                cluster_name: ${{secrets.GKE_CLUSTER}}
                location: ${{secrets.GKE_LOCATION}}
            
            - name: Deploy/Restart GKE Deployemnt
              run: kubectl rollout restart deployment client-depl
            