name: deploy-infra
on:
    push:
        branches:
            - master
        paths: 
            - 'infra/**'
    workflow_run: 
      workflows: ["terraform-deploy"] 
      types:
        - completed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Setup google cloud
              uses: google-github-actions/auth@v1
              with:
                project_id: ${{secrets.GKE_PROJECT_ID}} 
                credentials_json: ${{secrets.GKE_APPLICATION_CREDENTIALS}}
            
            - name: Connect to GKE
              uses: google-github-actions/get-gke-credentials@v0
              with:
                cluster_name: ${{secrets.GKE_CLUSTER}}
                location: ${{secrets.GKE_LOCATION}}
            
            - name: Deploy/Restart GKE Deployemnt
              run: kubectl apply -f infra/k8s
            