name: terraform-deploy
on:
    push:
        branches: 
            - master
        # paths: 
        #     - 'terraform/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GCP
              uses: actions/checkout@v2

            - name: Configure GCP
              uses: google-github-actions/auth@v1
              with:
                project_id:  ${{secrets.GKE_PROJECT_ID}} 
                credentials_json: ${{secrets.GKE_APPLICATION_CREDENTIALS}}

            - name: Configure Terraform
              run: |
                  echo "credentials \"app.terraform.io\" { token = \"$TF_API_TOKEN\" }" > ~/.terraformrc
              env:
               TF_API_TOKEN: ${{ secrets.TF_TOKEN }}
            
            - name: Configure Terraform
              run: cd terraform/infra && terraform init

            - name: Terraform Plan
              id: plan
              run: |
                   cd terraform/infra
                   terraform plan -out=tfplan
                   echo "::set-output name=has_changes::$(terraform plan -out=tfplan -detailed-exitcode | grep -E '^Changes\? false$' || echo 'true')"
              continue-on-error:  true

            - name: Terraform Apply
              if: steps.plan.outputs.has_changes == 'true'
              run: cd terraform/infra && ls -al && terraform apply --auto-approve tfplan && terraform output cluster_name

            - name: Trigger another workflow
              uses: peter-evans/repository-dispatch@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                event-type: "terraform-apply-complete"
               
