name: terraform-deploy
on:
    push:
        branches: 
            - master
        paths: 
            - 'terraform/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GCP
              uses: actions/checkout@v2

            - name: Connect to GCP
              uses: google-github-actions@v1
              with:
                project_id:  ${{secrets.GKE_PROJECT_ID}} 
                credentials_json: ${{secrets.GKE_APPLICATION_CREDENTIALS}}

            - name: Configure Terraform
              run: |
                  echo "credentials \"app.terraform.io\" { token = \"$TF_API_TOKEN\" }" > ~/.terraformrc
              env:
               TF_API_TOKEN: ${{ secrets.TF_TOKEN }}
            
            - name: Terraform commands
              run: terraform plan
